### PR TITLE
Add Investing Indonesia API

### PR DESCRIPTION
**Pull request by indrapalijama**
- add investing indonesia api
- fixing unused import and unused delete function in my previous api (voa indonesia and suara news)
- fixing apiList data in graphQL controller file
- edit readme-id.md files (forgot to add galangg's app in apps' showcase)
- edit readme.md files

Thanks!

edit : please do review my code, in case i've been doin something wrong or anything, anw i'd already test my function too and it's been working properly

### CODE REVIEW

**Comment by satyawikananda** [comment]
I've checked that API, but the return is 503, and this [base URL](http://id.investing.com/rss/) was forbidden.

API: https://berita-api-git-fork-indrapalijama-secondary-satyawikananda.vercel.app/v1/invest

**Comment by indrapalijama** [comment]
still not working tho, it looks like when built into production, the console doesn't shows up

**Comment by satyawikananda** [comment]
I've found the reason, I think the reason why the status code is returning 503, I think in `investing.com` site is using DDoS protection by Cloudflare, and when I hit `https://id.investing.com/rss/news.rss` on Postman, the return is 503 to.

image

What do you think?

**Comment by satyawikananda** [comment]
Okay, I'll close this now, thanks for your contributions :)

**Pull request closed without merging**
